# Generated by Django 5.2.7 on 2025-12-06 13:20

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1075_alter_document_checksum"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharelink",
            name="access_count",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                editable=False,
                help_text="The number of times the share link has been accessed.",
                verbose_name="access count",
            ),
        ),
        migrations.AddField(
            model_name="sharelink",
            name="max_access_count",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="The maximum number of times the share link can be accessed.",
                null=True,
                verbose_name="access count limit",
            ),
        ),
        migrations.AddField(
            model_name="sharelink",
            name="password_hash",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="The hashed password required to access the share link.",
                max_length=128,
                null=True,
                verbose_name="password hash",
            ),
        ),
        migrations.AddField(
            model_name="sharelink",
            name="protect_link_with_password",
            field=models.BooleanField(
                default=False,
                help_text="Determines whether the share link is protected with a password.",
                verbose_name="password protection",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="checksum",
            field=models.CharField(
                editable=False,
                help_text="The checksum of the original document.",
                max_length=32,
                unique=True,
                verbose_name="checksum",
            ),
        ),
        migrations.AlterField(
            model_name="sharelink",
            name="expiration",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="The date and time when the share link will expire.",
                null=True,
                verbose_name="expiration",
            ),
        ),
    ]
