# Generated by Django 5.2.7 on 2025-12-06 15:32

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        (
            "documents",
            "1076_sharelink_access_count_sharelink_max_access_count_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="checksum",
            field=models.CharField(
                db_index=True,
                editable=False,
                help_text="The checksum of the original document.",
                max_length=32,
                verbose_name="checksum",
            ),
        ),
    ]
