# Generated by Django 5.2.7 on 2026-01-02 03:11

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1077_alter_document_checksum"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="contains_PII",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Indicates whether the document contains Personally Identifiable Information (PII).",
                null=True,
                verbose_name="contains PII",
            ),
        ),
    ]
